name: Build AfifDesk Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: "latest"
